# Generated by Django 5.1.5 on 2025-03-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE TODAY', 'Due Today'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
